### ISSUE TITLE
Support linum / line numbers

### ISSUE THREAD

**Issue by gagbo** [MetroWind/flucui-theme#8]
Hello,

I'm using your nice theme just for the light part, with a toggle between light and dark themes, and I noticed that there is no setting for linum/linenumbers font-locks. I don't know what seems relevant to you, and I'm bad at this kind of stuff; can you please add them ?

I mean this kind of [faces](https://github.com/srcery-colors/srcery-emacs/blob/c0027f65ed6f6feb051eeab6e97c578cd486fc66/srcery-theme.el#L1556)

**Comment by MetroWind** [comment]
Will do. Thanks for the suggestion!

**Comment by MetroWind** [comment]
The linum face by default inherits from the “shadow” face, which is the same color in both themes. I have changed the shadow face to be the same color as comments, so it’s a bit different shades in light and dark.
